### ISSUE TITLE
test run failed

### ISSUE THREAD

**Issue by xuewuzhang-UTSW** [google-deepmind/alphafold3#101]
Hi My test run failed and showed the following error messages. Can you please give me a pointer to what went wrong? Thanks.

Running tests under Python 3.11.10: /alphafold3_venv/bin/python
[ RUN      ] InferenceTest.test_config
I1121 18:02:23.636471 140502211036288 xla_bridge.py:895] Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
I1121 18:02:23.638316 140502211036288 xla_bridge.py:895] Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory
[       OK ] InferenceTest.test_config
[ RUN      ] InferenceTest.test_featurisation
Processing chain A
I1121 18:02:23.674724 140502211036288 pipeline.py:40] Getting protein MSAs for sequence SEFEKLRQTGDELVQAFQRLREIFDKGDDDSLEQVLEEIEELIQKHRQLFDNRQEAADTEAAKQGDQWVQLFQRFREAIDKGDKDSLEQLLEELEQALQKIRELAEKKN
[  FAILED  ] InferenceTest.test_featurisation
[ RUN      ] InferenceTest.test_inference_bucket_1024
Processing fold input 5tgy
Checking we can load the model parameters...
Running data pipeline...
Processing chain A
I1121 18:02:28.576358 140502211036288 pipeline.py:40] Getting protein MSAs for sequence SEFEKLRQTGDELVQAFQRLREIFDKGDDDSLEQVLEEIEELIQKHRQLFDNRQEAADTEAAKQGDQWVQLFQRFREAIDKGDKDSLEQLLEELEQALQKIRELAEKKN
[  FAILED  ] InferenceTest.test_inference_bucket_1024
[ RUN      ] InferenceTest.test_inference_default_bucket
Processing fold input 5tgy
Checking we can load the model parameters...
Running data pipeline...
Processing chain A
I1121 18:02:31.834488 140502211036288 pipeline.py:40] Getting protein MSAs for sequence SEFEKLRQTGDELVQAFQRLREIFDKGDDDSLEQVLEEIEELIQKHRQLFDNRQEAADTEAAKQGDQWVQLFQRFREAIDKGDKDSLEQLLEELEQALQKIRELAEKKN
[  FAILED  ] InferenceTest.test_inference_default_bucket
[ RUN      ] InferenceTest.test_model_inference
/alphafold3_venv/lib/python3.11/site-packages/jax/_src/pjit.py:443: DeprecationWarning: backend and device argument on jit is deprecated. You can use `jax.device_put(..., jax.local_devices("cpu")[0])` on the inputs to the jitted function to get the same behavior.
  warnings.warn(
/alphafold3_venv/lib/python3.11/site-packages/jax/_src/linear_util.py:193: DeprecationWarning: Passing arguments 'a', 'a_min' or 'a_max' to jax.numpy.clip is deprecated. Please use 'arr', 'min' or 'max' respectively instead.
  ans = self.f(*args, **dict(self.params, **kwargs))
[  FAILED  ] InferenceTest.test_model_inference
[ RUN      ] InferenceTest.test_no_chains_in_input
Processing fold input empty
[       OK ] InferenceTest.test_no_chains_in_input
[ RUN      ] InferenceTest.test_process_fold_input_runs_only_data_pipeline
Processing fold input 5tgy
Running data pipeline...
Processing chain A
I1121 18:02:35.672044 140502211036288 pipeline.py:40] Getting protein MSAs for sequence SEFEKLRQTGDELVQAFQRLREIFDKGDDDSLEQVLEEIEELIQKHRQLFDNRQEAADTEAAKQGDQWVQLFQRFREAIDKGDKDSLEQLLEELEQALQKIRELAEKKN
[  FAILED  ] InferenceTest.test_process_fold_input_runs_only_data_pipeline
[ RUN      ] InferenceTest.test_process_fold_input_runs_only_inference
Processing fold input 5tgy
Checking we can load the model parameters...
Skipping data pipeline...
Output directory: <absl.testing.absltest._TempDir object at 0x7fc774395a10>
Writing model input JSON to <absl.testing.absltest._TempDir object at 0x7fc774395a10>
Predicting 3D structure for 5tgy for seed(s) (1234,)...
Featurising data for seeds (1234,)...
[       OK ] InferenceTest.test_process_fold_input_runs_only_inference
[ RUN      ] InferenceTest.test_replace_db_dir0 (num_db_dirs=1)
[       OK ] InferenceTest.test_replace_db_dir0 (num_db_dirs=1)
[ RUN      ] InferenceTest.test_replace_db_dir1 (num_db_dirs=2)
[       OK ] InferenceTest.test_replace_db_dir1 (num_db_dirs=2)
[ RUN      ] InferenceTest.test_write_input_json
[       OK ] InferenceTest.test_write_input_json
======================================================================
ERROR: test_featurisation (__main__.InferenceTest)
InferenceTest.test_featurisation
Run featurisation and assert that the output is as expected.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/alphafold/run_alphafold_test.py", line 217, in test_featurisation
    full_fold_input = data_pipeline.process(fold_input)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/pipeline.py", line 482, in process
    processed_chains.append(self.process_protein_chain(chain))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/pipeline.py", line 423, in process_protein_chain
    unpaired_msa, paired_msa, template_hits = _get_protein_msa_and_templates(
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/pipeline.py", line 69, in _get_protein_msa_and_templates
    uniref90_msa = uniref90_msa_future.result()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/msa.py", line 340, in get_msa
    a3m=get_msa_tool(run_config.config).query(target_sequence).a3m,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/msa.py", line 294, in get_msa_tool
    return jackhmmer.Jackhmmer(
           ^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/tools/jackhmmer.py", line 60, in __init__
    subprocess_utils.check_binary_exists(
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/tools/subprocess_utils.py", line 35, in check_binary_exists
    if not os.path.exists(path):
           ^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

======================================================================
ERROR: test_inference_bucket_1024 (__main__.InferenceTest)
InferenceTest.test_inference_bucket_1024
test_inference_bucket_1024(bucket=1024, exp_ranking_scores=[0.69, 0.71, 0.71, 0.69, 0.7])
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/testing/parameterized.py", line 319, in bound_param_test
    return test_method(self, **testcase_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/alphafold/run_alphafold_test.py", line 328, in test_inference
    actual = run_alphafold.process_fold_input(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/alphafold/run_alphafold.py", line 543, in process_fold_input
    fold_input = pipeline.DataPipeline(data_pipeline_config).process(fold_input)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/pipeline.py", line 482, in process
    processed_chains.append(self.process_protein_chain(chain))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/pipeline.py", line 423, in process_protein_chain
    unpaired_msa, paired_msa, template_hits = _get_protein_msa_and_templates(
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/pipeline.py", line 69, in _get_protein_msa_and_templates
    uniref90_msa = uniref90_msa_future.result()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/msa.py", line 340, in get_msa
    a3m=get_msa_tool(run_config.config).query(target_sequence).a3m,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/msa.py", line 294, in get_msa_tool
    return jackhmmer.Jackhmmer(
           ^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/tools/jackhmmer.py", line 60, in __init__
    subprocess_utils.check_binary_exists(
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/tools/subprocess_utils.py", line 35, in check_binary_exists
    if not os.path.exists(path):
           ^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

======================================================================
ERROR: test_inference_default_bucket (__main__.InferenceTest)
InferenceTest.test_inference_default_bucket
test_inference_default_bucket(bucket=None, exp_ranking_scores=[0.69, 0.69, 0.72, 0.75, 0.7])
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/testing/parameterized.py", line 319, in bound_param_test
    return test_method(self, **testcase_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/alphafold/run_alphafold_test.py", line 328, in test_inference
    actual = run_alphafold.process_fold_input(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/alphafold/run_alphafold.py", line 543, in process_fold_input
    fold_input = pipeline.DataPipeline(data_pipeline_config).process(fold_input)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/pipeline.py", line 482, in process
    processed_chains.append(self.process_protein_chain(chain))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/pipeline.py", line 423, in process_protein_chain
    unpaired_msa, paired_msa, template_hits = _get_protein_msa_and_templates(
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/pipeline.py", line 69, in _get_protein_msa_and_templates
    uniref90_msa = uniref90_msa_future.result()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/msa.py", line 340, in get_msa
    a3m=get_msa_tool(run_config.config).query(target_sequence).a3m,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/msa.py", line 294, in get_msa_tool
    return jackhmmer.Jackhmmer(
           ^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/tools/jackhmmer.py", line 60, in __init__
    subprocess_utils.check_binary_exists(
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/tools/subprocess_utils.py", line 35, in check_binary_exists
    if not os.path.exists(path):
           ^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

======================================================================
ERROR: test_model_inference (__main__.InferenceTest)
InferenceTest.test_model_inference
Run model inference and assert that the output is as expected.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/alphafold/run_alphafold_test.py", line 243, in test_model_inference
    inference_result = self._runner.run_inference(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/alphafold/run_alphafold.py", line 311, in run_inference
    result = self._model(rng_key, featurised_example)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/haiku/_src/transform.py", line 183, in apply_fn
    out, state = f.apply(params, None, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/haiku/_src/transform.py", line 457, in apply_fn
    except jax.errors.UnexpectedTracerError as e:
  File "/app/alphafold/run_alphafold.py", line 292, in forward_fn
    result = self._model_class(self._model_config)(batch)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/haiku/_src/module.py", line 464, in wrapped
    out = f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/haiku/_src/module.py", line 305, in run_interceptors
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/model/diffusion/model.py", line 279, in __call__
    embeddings, _ = hk.fori_loop(0, num_iter, recycle_body, (embeddings, key))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/haiku/_src/stateful.py", line 697, in fori_loop
    state, val = jax.lax.fori_loop(lower, upper, pure_body_fun, init_val)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/haiku/_src/stateful.py", line 677, in pure_body_fun
    val = body_fun(i, val)
          ^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/model/diffusion/model.py", line 252, in recycle_body
    embeddings = embedding_module(
                 ^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/haiku/_src/module.py", line 464, in wrapped
    out = f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/haiku/_src/module.py", line 305, in run_interceptors
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/model/diffusion/model.py", line 734, in __call__
    pair_activations, key = self._embed_template_pair(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/model/diffusion/model.py", line 644, in _embed_template_pair
    template_act = template_fn(
                   ^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/haiku/_src/module.py", line 464, in wrapped
    out = f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/haiku/_src/module.py", line 305, in run_interceptors
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/model/diffusion/template_modules.py", line 194, in __call__
    summed_template_embeddings, _ = hk.scan(
                                    ^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/haiku/_src/stateful.py", line 643, in scan
    (carry, state), ys = jax.lax.scan(
                         ^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/haiku/_src/stateful.py", line 626, in stateful_fun
    carry, out = f(carry, x)
                 ^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/model/diffusion/template_modules.py", line 182, in scan_fn
    embedding = template_embedder(
                ^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/haiku/_src/module.py", line 464, in wrapped
    out = f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/haiku/_src/module.py", line 305, in run_interceptors
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/model/diffusion/template_modules.py", line 348, in __call__
    act = template_stack(act)
          ^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/haiku/_src/layer_stack.py", line 403, in wrapped
    ret = mod(x=args, **kwargs)[0]
          ^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/haiku/_src/layer_stack.py", line 211, in __call__
    carry, (zs, states) = jax.lax.scan(
                          ^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/haiku/_src/layer_stack.py", line 195, in layer
    (out_x, z), state = apply_fn(
                        ^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/haiku/_src/transform.py", line 457, in apply_fn
    except jax.errors.UnexpectedTracerError as e:
  File "/alphafold3_venv/lib/python3.11/site-packages/haiku/_src/layer_stack.py", line 249, in _call_wrapped
    ret = self._f(*x, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/model/diffusion/template_modules.py", line 341, in template_iteration_fn
    return modules.PairFormerIteration(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/haiku/_src/module.py", line 464, in wrapped
    out = f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/haiku/_src/module.py", line 305, in run_interceptors
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/model/diffusion/modules.py", line 481, in __call__
    act += GridSelfAttention(
           ^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/haiku/_src/module.py", line 464, in wrapped
    out = f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/haiku/_src/module.py", line 305, in run_interceptors
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/model/diffusion/modules.py", line 228, in __call__
    act = mapping.inference_subbatch(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/model/components/mapping.py", line 295, in inference_subbatch
    output = sharded_module(*batched_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/model/components/mapping.py", line 148, in mapped_fn
    remainder_shape_dtype = hk.eval_shape(
                            ^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/haiku/_src/stateful.py", line 933, in eval_shape
    out_shape = jax.eval_shape(stateless_fun, internal_state(), *args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/haiku/_src/stateful.py", line 929, in stateless_fun
    out = fun(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/model/components/mapping.py", line 146, in apply_fun_to_slice
    return fun(*input_slice, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/model/components/mapping.py", line 279, in run_module
    res = module(*args)
          ^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/model/diffusion/modules.py", line 170, in _attention
    weighted_avg = attention.dot_product_attention(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/jax/attention/attention.py", line 127, in dot_product_attention
    raise ValueError(
ValueError: implementation='triton' for FlashAttention is unsupported on this GPU generation. Please use implementation='xla' instead.
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

======================================================================
ERROR: test_process_fold_input_runs_only_data_pipeline (__main__.InferenceTest)
InferenceTest.test_process_fold_input_runs_only_data_pipeline
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/alphafold/run_alphafold_test.py", line 264, in test_process_fold_input_runs_only_data_pipeline
    run_alphafold.process_fold_input(
  File "/app/alphafold/run_alphafold.py", line 543, in process_fold_input
    fold_input = pipeline.DataPipeline(data_pipeline_config).process(fold_input)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/pipeline.py", line 482, in process
    processed_chains.append(self.process_protein_chain(chain))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/pipeline.py", line 423, in process_protein_chain
    unpaired_msa, paired_msa, template_hits = _get_protein_msa_and_templates(
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/pipeline.py", line 69, in _get_protein_msa_and_templates
    uniref90_msa = uniref90_msa_future.result()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/msa.py", line 340, in get_msa
    a3m=get_msa_tool(run_config.config).query(target_sequence).a3m,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/msa.py", line 294, in get_msa_tool
    return jackhmmer.Jackhmmer(
           ^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/tools/jackhmmer.py", line 60, in __init__
    subprocess_utils.check_binary_exists(
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/tools/subprocess_utils.py", line 35, in check_binary_exists
    if not os.path.exists(path):
           ^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

----------------------------------------------------------------------
Ran 11 tests in 24.505s

FAILED (errors=5)

**Comment by jsspencer** [comment]
Either jackhmmer is not installed or it is not available on your PATH -- the test assumes `shutil.which` returns valid paths: https://github.com/google-deepmind/alphafold3/blob/main/run_alphafold_test.py#L45.

**Comment by xuewuzhang-UTSW** [comment]
Thanks. This is indeed the problem, due to proxy issue. I added the proxy and Jackhammer was installed successfully. I will close the issue now.
