### ISSUE TITLE
SMILES strings with a \ need to be escaped in input.json file

### ISSUE THREAD

**Issue by smg3d** [google-deepmind/alphafold3#110]
Some SMILES strings use the `\` character, which is not supported in the `input.json`. Note that rdkit supports these SMILES string without escaping the `\`, but I guess .json does not. It may be worth mentioning in the input doc that all `\` must be escaped in the SMILES definitions in `input.json`.

The following SMILES string :

```
"smiles": "[O-]P(OCC[N+](C)(C)C)(OC[C@]([H])(OC(CCCCCCC/C=C\CCCCCCCC)=O)COC(CCCCCCC/C=C\CCCCCCCC)=O)=O"
```

results in :

```
Traceback (most recent call last):
  File "/app/alphafold/run_alphafold.py", line 674, in <module>
    app.run(main)
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/app/alphafold/run_alphafold.py", line 580, in main
    fold_inputs = folding_input.load_fold_inputs_from_path(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/common/folding_input.py", line 1022, in load_fold_inputs_from_path
    raw_json = json.loads(json_str)
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Invalid \escape: line 19 column 68 (char 1278628)
```

The fix to the above error is to use :

"smiles": "[O-]P(OCC[N+](C)(C)C)(OC[C@]([H])(OC(CCCCCCC/C=C\\CCCCCCCC)=O)COC(CCCCCCC/C=C\\CCCCCCCC)=O)=O"
```

**Comment by ullahsamee** [comment]
Here's the solution:
1. Upload your ligand in any format to;
https://datascience.unm.edu/tomcat/biocomp/convert

2. Convert to SMILES
3. Feed as input to JSON AF3.

Enjoy!
