### ISSUE TITLE
How to run a single test?

### ISSUE THREAD

**Issue by jkosinski** [google-deepmind/alphafold3#129]
For AF3 friendly hacking, we'd like sometimes run a single test like:
```
python -m unittest run_alphafold_test.InferenceTest.test_no_chains_in_input
```
However, the above command throws:
```
======================================================================
ERROR: test_no_chains_in_input (run_alphafold_test.InferenceTest)
run_alphafold_test.InferenceTest.test_no_chains_in_input
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/g/kosinski/kosinski/devel/alphafold3/run_alphafold_test.py", line 189, in setUp
    model_dir=pathlib.Path(run_alphafold.MODEL_DIR.value),
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/g/kosinski/kosinski/software/envs/alphafold3/lib/python3.11/site-packages/absl/flags/_flagvalues.py", line 1426, in value
    val = getattr(self._flagvalues, self._name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/g/kosinski/kosinski/software/envs/alphafold3/lib/python3.11/site-packages/absl/flags/_flagvalues.py", line 498, in __getattr__
    raise _exceptions.UnparsedFlagAccessError(
absl.flags._exceptions.UnparsedFlagAccessError: Trying to access flag --model_dir before flags were parsed.

----------------------------------------------------------------------
Ran 1 test in 3.600s

FAILED (errors=1)
```
Do you have a way of running tests from run_alphafold_test.py individually?

**Comment by jsspencer** [comment]
You can pass the test name as an argument to `run_alphafold_test.py`, e.g.
```
$ python run_alphafold_test.py -- InferenceTest.test_write_input_json
Running tests under Python 3.11.10: /alphafold3_venv/bin/python
[ RUN      ] InferenceTest.test_write_input_json
[       OK ] InferenceTest.test_write_input_json
----------------------------------------------------------------------
Ran 1 test in 0.343s
```

**Comment by jkosinski** [comment]
Thank you!
