### ISSUE TITLE
Cannot skip running the data pipeline

### ISSUE THREAD

**Issue by RossoneriZhao** [google-deepmind/alphafold3#151]
I really want to see what would happen if I do not get protein MSAs, as this process is very time-consuming. Then I set "--run_data_pipeline=false" to skip running the data pipeline.

However, the running failed:
`Traceback (most recent call last):
  File "/app/alphafold/run_alphafold.py", line 680, in <module>
    app.run(main)
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/app/alphafold/run_alphafold.py", line 665, in main
    process_fold_input(
  File "/app/alphafold/run_alphafold.py", line 544, in process_fold_input
    all_inference_results = predict_structure(
                            ^^^^^^^^^^^^^^^^^^
  File "/app/alphafold/run_alphafold.py", line 362, in predict_structure
    featurised_examples = featurisation.featurise_input(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/featurisation.py", line 62, in featurise_input
    validate_fold_input(fold_input)
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/featurisation.py", line 28, in validate_fold_input
    raise ValueError(f'Protein chain {i + 1} is missing unpaired MSA.')
ValueError: Protein chain 1 is missing unpaired MSA.`

It seems that getting MSAs is necessary, or rather, do I need to make other additional settings?

**Comment by alchemistcai** [comment]
In protein json definition,set `unpairedMsa` and `pairedMsa` as `""` explicitly.

Also,template may need to set as [] explicitly.

```json
{
  "protein": {
    "id": "A",
    "sequence": ...,
    "unpairedMsa": "",
    "pairedMsa": "",
    "templates": []
  }
}
```

Hope this helps you @RossoneriZhao

**Comment by Daniel-Halvey** [comment]
Thank you.


Best,
Daniel
________________________________

**Comment by RossoneriZhao** [comment]
Thank you very much for your reply, my problem has been solved
