### ISSUE TITLE
 ValueError: Unexpected JSON keys in: ligand 

### ISSUE THREAD

**Issue by GUMI-QXP** [google-deepmind/alphafold3#161]
Why do I prompt ValueError: 

```
Unexpected JSON keys in: ligand when using ligand input
I1203 15:24:08.423259 123143367554880 folding_input.py:1044] Detected /home/qxp/AF3/alphafold3/oncokb_smiles_json/1.json is an AlphaFold 3 JSON since the top-level is not a list.
Traceback (most recent call last):
  File "/home/qxp/anaconda3/envs/AF3-qxp/lib/python3.11/site-packages/alphafold3/common/folding_input.py", line 1050, in load_fold_inputs_from_path
    fold_inputs.append(Input.from_json(json_str))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qxp/anaconda3/envs/AF3-qxp/lib/python3.11/site-packages/alphafold3/common/folding_input.py", line 667, in from_json
    _validate_keys(
  File "/home/qxp/anaconda3/envs/AF3-qxp/lib/python3.11/site-packages/alphafold3/common/folding_input.py", line 43, in _validate_keys
    raise ValueError(f'Unexpected JSON keys in: {", ".join(sorted(bad_keys))}')
ValueError: Unexpected JSON keys in: ligand

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/qxp/AF3/alphafold3/run_alphafold.py", line 704, in <module>
    app.run(main)
  File "/home/qxp/anaconda3/envs/AF3-qxp/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/qxp/anaconda3/envs/AF3-qxp/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/home/qxp/AF3/alphafold3/run_alphafold.py", line 603, in main
    fold_inputs = folding_input.load_fold_inputs_from_path(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qxp/anaconda3/envs/AF3-qxp/lib/python3.11/site-packages/alphafold3/common/folding_input.py", line 1052, in load_fold_inputs_from_path
    raise ValueError(
ValueError: Failed to load fold input from /home/qxp/AF3/alphafold3/oncokb_smiles_json/1.json. The JSON at /home/qxp/AF3/alphafold3/oncokb_smiles_json/1.json was detected to be an AlphaFold 3 JSON since the top-level is not a list.
```

I followed the given input format

**Comment by GUMI-QXP** [comment]
{
    "ligand": {
        "id": "A",
        "smiles": "C[C@H](CCCC(C)C)[C@H]1CC[C@@H]2[C@@]1(CC[C@H]3C2=CC=C4[C@@]3(CC[C@@H](C4)O)C)C"
    }
}
this is my data

**Comment by alchemistcai** [comment]
It seems like that your json file is incomplete.

It should be:

```json
{
  "name": "Your job name",
  "modelSeeds": [42],
  "sequences": [
    {
      "ligand": {
        "id": "A",
        "smiles": "Your smiles"
      }
    }
  ],
  "dialect": "alphafold3",
  "version": 1
}
```

See [input doc](https://github.com/google-deepmind/alphafold3/blob/main/docs/input.md) for more information.

**Comment by Augustin-Zidek** [comment]
Thanks @alchemistcai for answering! Your input should be:


```json
{
  "name": "Your job name",
  "modelSeeds": [42],
  "sequences": [
    {
      "ligand": {
        "id": "A",
        "smiles": "C[C@H](CCCC(C)C)[C@H]1CC[C@@H]2[C@@]1(CC[C@H]3C2=CC=C4[C@@]3(CC[C@@H](C4)O)C)C"
      }
    }
  ],
  "dialect": "alphafold3",
  "version": 1
}
```
