### ISSUE TITLE
crosslinking add on to alphafold3

### ISSUE THREAD

**Issue by fglaser** [google-deepmind/alphafold3#194]
Dear Prof. Kosinski, 

This is really a wonderful addition!

I would like very much to try it, and I think I succeded to install it, as it the suggested installation procedure produced no error after some tweaking. The I tried to run your example, but I got the following  error pasted below. I understand it does not recognize the crosslink key, and I am not sure how to proceed. 

Just as a test, when I remove the crosslink section, alphafold3 runs perfectly well.

Maybe I am doing a trivial mistake and some directory of alphafold3x needs to be added to some location in alphafold3 installation?

Thanks a lot in advance, and again great addition!

Fabian
Technion, Israel

bash test2.sh
I1208 09:34:03.112920 140226657427456 folding_input.py:1046] Detected /root/af_input/test2.json is an AlphaFold 3 JSON since the top-level is not a list.
Traceback (most recent call last):
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/common/folding_input.py", line 1052, in load_fold_inputs_from_path
    fold_inputs.append(Input.from_json(json_str))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/common/folding_input.py", line 667, in from_json
    _validate_keys(
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/common/folding_input.py", line 43, in _validate_keys
    raise ValueError(f'Unexpected JSON keys in: {", ".join(sorted(bad_keys))}')
ValueError: Unexpected JSON keys in: crosslinks

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/alphafold/run_alphafold.py", line 716, in <module>
    app.run(main)
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/app/alphafold/run_alphafold.py", line 613, in main
    fold_inputs = folding_input.load_fold_inputs_from_path(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/common/folding_input.py", line 1054, in load_fold_inputs_from_path
    raise ValueError(
ValueError: Failed to load fold input from /root/af_input/test2.json. The JSON at /root/af_input/test2.json was detected to be an AlphaFold 3 JSON since the top-level is not a list.

**Comment by jkosinski** [comment]
Hi Fabian, it seems more like something went wrong with the installation and you still using the original alphafold library, maybe you have both in your PYTHONPATH or other environment, but before you respond, could you repost this issue at https://github.com/KosinskiLab/alphafold3x as this GitHub I guess should be used for the original alphafold repo.

**Comment by fglaser** [comment]
Sorry for the duplication, I was trying to copy it to alphafold3x but obviously I did not do right.

Thanks,
Fabian
