### ISSUE TITLE
userCCD input issue

### ISSUE THREAD

**Issue by xuewuzhang-UTSW** [google-deepmind/alphafold3#198]
I noticed an unexpected behavior when specifying a ligand with userCCD: the job would fail if the "ccdCodes" field is a list of str, for example: "ccdCodes": ["Lig-1"]. However, it runs fine if a simple str is provided: "ccdCodes": "Lig-1".  This behavior is inconsistent with the input documentation, where it says that the ccdCodes should be a list of strings.

I paste the error message below:
 Traceback (most recent call last):
  File "/app/alphafold/run_alphafold_1.py", line 706, in <module>
    app.run(main)
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/app/alphafold/run_alphafold_1.py", line 691, in main
    process_fold_input(
  File "/app/alphafold/run_alphafold_1.py", line 561, in process_fold_input
    all_inference_results = predict_structure(
                            ^^^^^^^^^^^^^^^^^^
  File "/app/alphafold/run_alphafold_1.py", line 365, in predict_structure
    featurised_examples = featurisation.featurise_input(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/featurisation.py", line 76, in featurise_input
    batch = data_pipeline.process_item(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/model/pipeline/pipeline.py", line 166, in process_item
    struct = fold_input.to_structure(ccd=ccd)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/common/folding_input.py", line 955, in to_structure
    struc = structure.from_sequences_and_bonds(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/structure/parsing.py", line 743, in from_sequences_and_bonds
    chem_comp_data = struc_chem_comps.populate_missing_ccd_data(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/structure/chemical_components.py", line 214, in populate_missing_ccd_data
    ccd_data = get_data_for_ccd_components(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/structure/chemical_components.py", line 168, in get_data_for_ccd_components
    chem_data = chemical_components.component_name_to_info(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/constants/chemical_components.py", line 165, in component_name_to_info
    return mmcif_to_info(component)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/constants/chemical_components.py", line 139, in mmcif_to_info
    descriptor_types = mmcif['_pdbx_chem_comp_descriptor.type']
                       ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '_pdbx_chem_comp_descriptor.type'

**Comment by xuewuzhang-UTSW** [comment]
Ok, this issue might be related to issue #178. "_pdbx_chem_comp_descriptor.type" and "_pdbx_chem_comp_descriptor.descriptor" need to be included in the userCCD, although they are not used.

**Comment by xuewuzhang-UTSW** [comment]
I realized that using str in the ccdCodes field didn't really fix the issue. AlpahFold simply ignored the userCCD and used the compound from the database based on the name that I used. 

This issue may be related to issue #178. It says "_pdbx_chem_comp_descriptor.type" and "_pdbx_chem_comp_descriptor.descriptor" need to be provided although they are not used.

**Comment by Augustin-Zidek** [comment]
This has been fixed in https://github.com/google-deepmind/alphafold3/commit/63132c4e46479512041ef69583a4b07854c21468 -- could you update your AlphaFold installation to get the fix?

**Comment by xuewuzhang-UTSW** [comment]
Got it. Thanks!
