### ISSUE TITLE
UserCCD error

### ISSUE THREAD

**Issue by yjzh1982** [google-deepmind/alphafold3#204]
Hi Everyone, 

I got an error when I tried to run alphafold3 using "userCCD". The error message is as below. 

Traceback (most recent call last):
  File "/home/u000013203832/af3_demo/run_alphafold.py", line 678, in <module>
    app.run(main)
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/home/u000013203832/af3_demo/run_alphafold.py", line 663, in main
    process_fold_input(
  File "/home/u000013203832/af3_demo/run_alphafold.py", line 542, in process_fold_input
    all_inference_results = predict_structure(
                            ^^^^^^^^^^^^^^^^^^
  File "/home/u000013203832/af3_demo/run_alphafold.py", line 362, in predict_structure
    featurised_examples = featurisation.featurise_input(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/featurisation.py", line 76, in featurise_input
    batch = data_pipeline.process_item(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/model/pipeline/pipeline.py", line 166, in process_item
    struct = fold_input.to_structure(ccd=ccd)****
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/common/folding_input.py", line 953, in to_structure
    struc = structure.from_sequences_and_bonds(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/structure/parsing.py", line 743, in from_sequences_and_bonds
    chem_comp_data = struc_chem_comps.populate_missing_ccd_data(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/structure/chemical_components.py", line 214, in populate_missing_ccd_data
    ccd_data = get_data_for_ccd_components(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/structure/chemical_components.py", line 168, in get_data_for_ccd_components
    chem_data = chemical_components.component_name_to_info(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/constants/chemical_components.py", line 165, in component_name_to_info
    return mmcif_to_info(component)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/constants/chemical_components.py", line 119, in mmcif_to_info
    pdbx_synonyms = mmcif['_chem_comp.pdbx_synonyms']
                    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '_chem_comp.pdbx_synonyms'

My input file is attached.  Could you please help me fix the problem?

Thanks,
BeWier

[wt.json](https://github.com/user-attachments/files/18092263/wt.json)

**Comment by ullahsamee** [comment]
@joshabramson 

If the ligand is (available in pdbechem) then simply define via ccdCodes and If its custom then via SMILES in the input JSON.

JSON input via ccdCodes:
![Screenshot from 2024-12-11 12-46-40](https://github.com/user-attachments/assets/85c8af28-cc2f-4e87-87cf-371244c5fea3) 

JSON input via SMILES(works both for custom/pdbechem):
![Screenshot from 2024-12-11 12-47-07](https://github.com/user-attachments/assets/1144d0eb-9048-4ebd-bdf7-160f88b3e398)

If the ligand is bonded to other entities, then it can be defined using the [CCD mmCIF format](https://www.wwpdb.org/data/ccd#mmcifFormat)

Once defined, then you can follow the rest of instructions here:
https://github.com/google-deepmind/alphafold3/blob/main/docs/input.md#user-provided-ccd:~:text=Once%20defined%2C%20this,named%20atom%20scheme.

Furthermore you can search CCD codes at:
https://www.ebi.ac.uk/pdbe-srv/pdbechem/
http://ligand-expo.rcsb.org/ld-search.html


Anyway, I predicted the complex for you via AF3 with CCDcode: X7F as input JSON if this is your ligand.
![X7F](https://github.com/user-attachments/assets/9b06512e-7937-43aa-9d5a-476b36cfbc08)

Here's the cif file:
[complex12_model.zip](https://github.com/user-attachments/files/18100172/complex12_model.zip)

**Comment by ullahsamee** [comment]
@yjzh1982 Here I corrected your json file and also run it.
[wtcorrected.json](https://github.com/user-attachments/files/18101191/wtcorrected.json)

[testx7f.zip](https://github.com/user-attachments/files/18101268/testx7f.zip)

![last](https://github.com/user-attachments/assets/51f14ee6-49c5-435f-8a24-a413702cfca4)
