### ISSUE TITLE
CUDA_ERROR_OUT_OF_MEMORY issue when running test case on 4090 24G GPU machine locally

### ISSUE THREAD

**Issue by MaoSihong** [google-deepmind/alphafold3#209]
when I launched the 2PV7 test case with all default profile, I encountered following err after MSA pipeline(it seems so):
![image](https://github.com/user-attachments/assets/ef01c792-3207-48e9-8ee6-5801b8e81560)
![image](https://github.com/user-attachments/assets/704a10ae-043a-4a72-aa03-3d3605e636be)
I also tried the mentioned troubleshooting set:

```
ENV XLA_PYTHON_CLIENT_PREALLOCATE=false
ENV TF_FORCE_UNIFIED_MEMORY=true
ENV XLA_CLIENT_MEM_FRACTION=3.2
and modified model_config.py:
  pair_transition_shard_spec: Sequence[_Shape2DType] = (
      (2048, None),
      (3072, 1024),
      (None, 512),
  )
```

but still got errors at very beginning this time,no matter whether the --norun_data_pipeline was used:
![image](https://github.com/user-attachments/assets/c6d040c2-37fb-44f6-b2d0-0f89ecd71012)
any advice are appreciated!
link my docker run --rm --gpus all nvidia/cuda:12.6.0-base-ubuntu22.04 nvidia-smi here:
![image](https://github.com/user-attachments/assets/17cf67c2-22b5-44cb-a761-59884ef3a0f5)

**Comment by MaoSihong** [comment]
additionally I noticed that the container have low RAM costs when the test case is running at its MSA searching stage(usually less than 5GB). I dont know if it is the normal case for 2PV7

**Comment by MaoSihong** [comment]
> additionally I noticed that the container have low RAM costs when the test case is running at its MSA searching stage(usually less than 5GB). I dont know if it is the normal case for 2PV7
also following notice under default profile running
![image](https://github.com/user-attachments/assets/3f90d207-f55b-4657-818d-3057cbc1e489)

**Comment by joshabramson** [comment]
The error is during the inference stage, after msa.

As well as @alchemistcai being able to run on 4060, other users have reported success for this example on RTX 4090: https://github.com/google-deepmind/alphafold3/issues/59#issuecomment-2482720962 

It should be fine having two gpu available, but perhaps that is causing an issue for some reason, can you try with `--gpus device=0` instead of `--gpus all` ?

**Comment by MaoSihong** [comment]
> The error is during the inference stage, after msa.
> 
> As well as @alchemistcai being able to run on 4060, other users have reported success for this example on RTX 4090: [#59 (comment)](https://github.com/google-deepmind/alphafold3/issues/59#issuecomment-2482720962)
> 
> It should be fine having two gpu available, but perhaps that is causing an issue for some reason, can you try with `--gpus device=0` instead of `--gpus all` ?

![image](https://github.com/user-attachments/assets/8199c076-6738-4c72-baef-0adfe0010113)
sorry for that, I still failed

**Comment by alchemistcai** [comment]
> ENV XLA_PYTHON_CLIENT_PREALLOCATE=false
> ENV TF_FORCE_UNIFIED_MEMORY=true
> ENV XLA_CLIENT_MEM_FRACTION=3.2
> and modified model_config.py:
>   pair_transition_shard_spec: Sequence[_Shape2DType] = (
>       (2048, None),
>       (3072, 1024),
>       (None, 512),
>   )

You may try to undo this modification.I tried it before.

For a single GPU,uniform memory settings makes even 256 tokens inference OutOfMemory on 4060.

**Comment by XIANZHE-LI** [comment]
I've the same problem.

W external/xla/xla/service/hlo_rematerialization.cc:3005] Can't reduce memory use below 18.88GiB (20266891105 bytes) by rematerialization; only reduced to 41.43GiB (44490724824 bytes), down from 45.92GiB (49309847144 bytes) originally
2024-12-14 19:57:44.462633: W external/xla/xla/tsl/framework/bfc_allocator.cc:497] Allocator (GPU_0_bfc) ran out of memory trying to allocate 47.20GiB (rounded to 50677266944)requested by op 
2024-12-14 19:57:44.464119: W external/xla/xla/tsl/framework/bfc_allocator.cc:508] ************________________________________________________________________________________________
E1214 19:57:44.464390   17928 pjrt_stream_executor_client.cc:3084] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 50677266816 bytes.
Traceback (most recent call last):
  File "/root/lanyun-tmp/AF3/alphafold3/run_alphafold_exit.py", line 690, in <module>
    app.run(main)
  File "/root/miniconda/envs/af3-2/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/root/miniconda/envs/af3-2/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/root/lanyun-tmp/AF3/alphafold3/run_alphafold_exit.py", line 674, in main
    process_fold_input(
  File "/root/lanyun-tmp/AF3/alphafold3/run_alphafold_exit.py", line 542, in process_fold_input
    all_inference_results = predict_structure(
                            ^^^^^^^^^^^^^^^^^^
  File "/root/lanyun-tmp/AF3/alphafold3/run_alphafold_exit.py", line 375, in predict_structure
    result = model_runner.run_inference(example, rng_key)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/lanyun-tmp/AF3/alphafold3/run_alphafold_exit.py", line 313, in run_inference
    result = self._model(rng_key, featurised_example)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 50677266816 bytes.
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
![image](https://github.com/user-attachments/assets/bb93ea61-9631-45d1-8f36-eb3329fdb5c2)
i have 3 4090
but only can be used
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090        On  |   00000000:3D:00.0 Off |                  Off |
| 30%   28C    P8             15W /  450W |   23399MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA GeForce RTX 4090        On  |   00000000:63:00.0 Off |                  Off |
| 30%   29C    P8             21W /  450W |     393MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA GeForce RTX 4090        On  |   00000000:BD:00.0 Off |                  Off |
| 30%   27C    P8             19W /  450W |     393MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

**Comment by MaoSihong** [comment]
> > ENV XLA_PYTHON_CLIENT_PREALLOCATE=false
> > ENV TF_FORCE_UNIFIED_MEMORY=true
> > ENV XLA_CLIENT_MEM_FRACTION=3.2
> > and modified model_config.py:
> > pair_transition_shard_spec: Sequence[_Shape2DType] = (
> > (2048, None),
> > (3072, 1024),
> > (None, 512),
> > )
> 
> You may try to undo this modification.I tried it before.
> 
> For a single GPU,uniform memory settings makes even 256 tokens inference OutOfMemory on 4060.

yep, but at my first test with default PARAs, those ENV PARAs are not turned on.
but OOM failure still happened that time.
thank you very much for your close attention!

**Comment by MaoSihong** [comment]
> I've the same problem.
> 
> ```
> W external/xla/xla/service/hlo_rematerialization.cc:3005] Can't reduce memory use below 18.88GiB (20266891105 bytes) by rematerialization; only reduced to 41.43GiB (44490724824 bytes), down from 45.92GiB (49309847144 bytes) originally
> 2024-12-14 19:57:44.462633: W external/xla/xla/tsl/framework/bfc_allocator.cc:497] Allocator (GPU_0_bfc) ran out of memory trying to allocate 47.20GiB (rounded to 50677266944)requested by op 
> 2024-12-14 19:57:44.464119: W external/xla/xla/tsl/framework/bfc_allocator.cc:508] ************________________________________________________________________________________________
> E1214 19:57:44.464390   17928 pjrt_stream_executor_client.cc:3084] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 50677266816 bytes.
> Traceback (most recent call last):
>   File "/root/lanyun-tmp/AF3/alphafold3/run_alphafold_exit.py", line 690, in <module>
>     app.run(main)
>   File "/root/miniconda/envs/af3-2/lib/python3.11/site-packages/absl/app.py", line 308, in run
>     _run_main(main, args)
>   File "/root/miniconda/envs/af3-2/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
>     sys.exit(main(argv))
>              ^^^^^^^^^^
>   File "/root/lanyun-tmp/AF3/alphafold3/run_alphafold_exit.py", line 674, in main
>     process_fold_input(
>   File "/root/lanyun-tmp/AF3/alphafold3/run_alphafold_exit.py", line 542, in process_fold_input
>     all_inference_results = predict_structure(
>                             ^^^^^^^^^^^^^^^^^^
>   File "/root/lanyun-tmp/AF3/alphafold3/run_alphafold_exit.py", line 375, in predict_structure
>     result = model_runner.run_inference(example, rng_key)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/root/lanyun-tmp/AF3/alphafold3/run_alphafold_exit.py", line 313, in run_inference
>     result = self._model(rng_key, featurised_example)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 50677266816 bytes.
> --------------------
> ```
> 
> For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these. ![image](https://private-user-images.githubusercontent.com/113411292/395779938-bb93ea61-9631-45d1-8f36-eb3329fdb5c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMTg5NDYsIm5iZiI6MTczNDMxODY0NiwicGF0aCI6Ii8xMTM0MTEyOTIvMzk1Nzc5OTM4LWJiOTNlYTYxLTk2MzEtNDVkMS04ZjM2LWViMzMyOWZkYjVjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQwMzEwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjkzYzk4M2UyMmZmNWMxNWE5MWM4OTRlYmU0ZTM4MjEwZjNhYWU3MDNkZWYxYzIxNDcxNmY4NTk4YTBhMGNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5pvs_IbUrKphlX-0k-risqNcHvash2B8JgJ7jaTnWb4) i have 3 4090 but only can be used
> 
> ```
> | NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
> |-----------------------------------------+------------------------+----------------------+
> | GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
> |                                         |                        |               MIG M. |
> |=========================================+========================+======================|
> |   0  NVIDIA GeForce RTX 4090        On  |   00000000:3D:00.0 Off |                  Off |
> | 30%   28C    P8             15W /  450W |   23399MiB /  24564MiB |      0%      Default |
> |                                         |                        |                  N/A |
> +-----------------------------------------+------------------------+----------------------+
> |   1  NVIDIA GeForce RTX 4090        On  |   00000000:63:00.0 Off |                  Off |
> | 30%   29C    P8             21W /  450W |     393MiB /  24564MiB |      0%      Default |
> |                                         |                        |                  N/A |
> +-----------------------------------------+------------------------+----------------------+
> |   2  NVIDIA GeForce RTX 4090        On  |   00000000:BD:00.0 Off |                  Off |
> | 30%   27C    P8             19W /  450W |     393MiB /  24564MiB |      0%      Default |
> |                                         |                        |                  N/A |
> +-----------------------------------------+------------------------+----------------------+
> ```

sure I'll try to dig out the inside details without log filtering.
as far as I know, also only single GPU were allocated when my container was running

**Comment by MaoSihong** [comment]
> 错误发生在推理阶段，在 msa 之后。
> 
> 也@alchemistcai能够在 4060 上运行，其他用户报告此示例在 RTX 4090 上成功运行：[#59（评论）](https://github.com/google-deepmind/alphafold3/issues/59#issuecomment-2482720962)
> 
> 有两个可用的 GPU 应该没问题，但也许由于某种原因导致了问题，您可以尝试用`--gpus device=0`而不是 吗`--gpus all`？

yes I tried it yet with explicitly assignment of device=0, in fact no matter 'all' or 'device=0' option was on ,there's always device0 4090 24GB GPU showing significant resources occupy, but same OOM error occured

**Comment by Augustin-Zidek** [comment]
@MaoSihong from the screenshots, it looks like you are on the 560 version of NVIDIA drivers, i.e. on the beta channel. Could you try downgrading to the stable 550 version?

**Comment by MaoSihong** [comment]
> @MaoSihong从`nvidia-smi`截图来看，您使用的是 NVIDIA 驱动程序的 560 版本，即测试版。您可以尝试降级到稳定的 550 版本吗？
> 
> 或者这是在 Windows 下的 Linux 子系统？如果是这样，我强烈建议在 Linux 下运行 AlphaFold 3，这是唯一受支持的操作系统。
yep I made the case under the WSL2+docker desktop, docker can integrate to the subsystem. I dont know whether is the cuda version or subsystem cause the OOM. I think I should probably quit this struggling process on WSL2, seems that there is complicated compatibility problem for launching af3 in WSL

**Comment by Augustin-Zidek** [comment]
Agreed, I think running this natively under Linux will hopefully fix the issue. Feel free to comment or open a new issue if not.
