### ISSUE TITLE
ValueError: Failed to load fold input from fold_input.json. The JSON at fold_input.json was detected to be an AlphaFold 3 JSON since the top-level is not a list.

### ISSUE THREAD

**Issue by LasseMiddendorf** [google-deepmind/alphafold3#224]
Hello!

I'm trying to run AlphaFold3 using apptainer (version 1.3.5-1.el9), but it raises the following error, whenever I try to make it run with an input json that follows version 2 of the formatting:

```
Traceback (most recent call last):
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/common/folding_input.py", line 1050, in load_fold_inputs_from_path
    fold_inputs.append(Input.from_json(json_str))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/common/folding_input.py", line 693, in from_json
    raise ValueError(
ValueError: AlphaFold 3 input JSON has unsupported version: 2, expected 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/alphafold3/run_alphafold.py", line 738, in <module>
    app.run(main)
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/alphafold3/run_alphafold.py", line 622, in main
    fold_inputs = folding_input.load_fold_inputs_from_path(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/common/folding_input.py", line 1052, in load_fold_inputs_from_path
    raise ValueError(
ValueError: Failed to load fold input from fold_input.json. The JSON at fold_input.json was detected to be an AlphaFold 3 JSON since the top-level is not a list.
```

The same behavior was observed in #193, but the proposed solution didn't work for me. 

The json I'm using is:

```
{
  "name": "test",
  "sequences": [
    {
      "protein": {
        "id": ["A", "B"],
        "sequence": "<Sequence>",
        "unpairedMsa": "",
        "pairedMsa": "",
        "templates": []
      }
    }
  ],
  "modelSeeds": [1],
  "dialect": "alphafold3",
  "version": 2
} 
```

and I'm running AF3 with the command:

```
apptainer exec \
     --nv \
     --bind $HOME/alphafold3:/root/af_input \
     --bind $HOME/alphafold3:/root/af_output \
     --bind /software/sit/images/alphafold/3.0.0/models/:/root/models \
     --bind /db/alphafold3/202412/:/root/public_databases \
     /software/sit/images/alphafold/3.0.0/alphafold-3.0.0.sif \
     python run_alphafold.py \
     --json_path=fold_input.json \
     --output_dir=./output/ \
     --run_data_pipeline=False \
     --model_dir=/root/models

```

Would be great if anyone could help me with that! Thanks!

**Comment by Augustin-Zidek** [comment]
The problem is with the `"version": 2` line. You need to update your AlphaFold 3 installation to the latest version that supports this format. Or -- since you are not using any features from the second version -- just change it to `"version": 1` and you should be good to go.

Refer to https://github.com/google-deepmind/alphafold3/blob/main/docs/input.md#versions for more details about the version change.
