### ISSUE TITLE
Problem acquiring databases

### ISSUE THREAD

**Issue by almeida85** [google-deepmind/alphafold3#50]
Hello,

I am having problems downloading and decompressing the databases, specifically `pdb_2022_09_28_mmcif_files.tar.zst`, see below:
```

STARTING decompressing of mgy_clusters_2022_05.fa.zst
/data-beegfs/AlphaFold/DBs_AF3/nt_rna_2023_02_23_clust_seq_id_90_cov_80_rep_seq.fasta.zst: 80977012680 bytes 
FINISHED decompressing of nt_rna_2023_02_23_clust_seq_id_90_cov_80_rep_seq.fasta.zst
/data-beegfs/AlphaFold/DBs_AF3/mgy_clusters_2022_05.fa.zst: 128579703018 bytes 
FINISHED decompressing of mgy_clusters_2022_05.fa.zst
Traceback (most recent call last):
  File "fetch_databases.py", line 137, in <module>
    main(sys.argv[1:])
  File "fetch_databases.py", line 125, in main
    DATABASE_FILES,
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "fetch_databases.py", line 68, in download_and_decompress
    universal_newlines=True,
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '('curl', '--progress-bar', '--continue-at', '-', '--output', '/data-beegfs/AlphaFold/DBs_AF3/pdb_2022_09_28_mmcif_files.tar.zst', 'https://storage.googleapis.com/alphafold-databases/v3.0/pdb_2022_09_28_mmcif_files.tar.zst', '--stderr', '/dev/stdout')' returned non-zero exit status 18.
```

Any help will be appreciated.

Also, can I use the same databases of AF2?

**Comment by jsspencer** [comment]
Can you check that you have enough disk space? This error occurs if you fill up the disk where the files are being downloaded and uncompressed. The download size is ~250GB and uncompressed size is ~630GB. Please see [installation documentation](https://github.com/google-deepmind/alphafold3/blob/main/docs/installation.md#obtaining-genetic-databases) for more details.

**Comment by almeida85** [comment]
It seems it was a connection problem. I downloaded and decompressed all the databases.

Thanks
