### ISSUE TITLE
split stages into cpu and gpu

### ISSUE THREAD

**Issue by rukibuki** [google-deepmind/alphafold3#85]
I was testing how to split the CPU stage from the GPU stage using the "--norun_data_pipeline" &  "--norun_inference" flags.

Based on the log, the --norun_inference ran successfully, but it only yielded a single json output file.
[AF3 input json for --norun_inference](https://gist.github.com/rukibuki/39091fd38a7b37a24f01b6d589d06d14
)
[AF3 --norun_inference log]( https://gist.github.com/rukibuki/b8223f9c1ac48b35c01679d1db629867)
[AF3 --norun_inference output json](https://gist.github.com/rukibuki/be40ee67693e6300d612ed0c0c440223)

I then started a --norun_data_pipeline run by exchanging the" --norun_inference" flag with "--norun_data_pipeline". But it failed with:

Found local devices: [CudaDevice(id=0)]
Building model from scratch...
Processing 1 fold inputs.
Processing fold input C4D_TYS
Checking we can load the model parameters...
Skipping data pipeline...
Output directory: /root/af_output/c4d_tys
Writing model input JSON to /root/af_output/c4d_tys
Predicting 3D structure for C4D_TYS for seed(s) (1,)...
Featurising data for seeds (1,)...
Traceback (most recent call last):
  File "/root/alphafold3/run_alphafold.py", line 678, in <module>
    app.run(main)
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/root/alphafold3/run_alphafold.py", line 663, in main
    process_fold_input(
  File "/root/alphafold3/run_alphafold.py", line 542, in process_fold_input
    all_inference_results = predict_structure(
                            ^^^^^^^^^^^^^^^^^^
  File "/root/alphafold3/run_alphafold.py", line 362, in predict_structure
    featurised_examples = featurisation.featurise_input(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/featurisation.py", line 62, in featurise_input
    validate_fold_input(fold_input)
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/featurisation.py", line 28, in validate_fold_input
    raise ValueError(f'Protein chain {i + 1} is missing unpaired MSA.')
ValueError: Protein chain 1 is missing unpaired MSA.

The same input json works fine in a regular AF3 pipeline (no splitting of stages).

What am I missing here? I was unsure if the correct way to initiate the --norun_data_pipeline was to do as I did, but I don't see any other output files so I could not think of another way.

**Comment by rukibuki** [comment]
> In the GPU stage, you need to use the yielded json file from the CPU stage as the input.

ahh ye sI did not say or show that,m but I did that also. so I used the output json from the --norun_inference run as input for the --nnorun_data_pipeline run, but I get this:
Skipping running the data pipeline.
Found local devices: [CudaDevice(id=0)]
Building model from scratch...
Processing 1 fold inputs.
Processing fold input C4D_TYS
Checking we can load the model parameters...
Skipping data pipeline...
Output directory: /root/af_output/c4d_tys
Writing model input JSON to /root/af_output/c4d_tys
Predicting 3D structure for C4D_TYS for seed(s) (1,)...
Featurising data for seeds (1,)...
Traceback (most recent call last):
  File "/root/alphafold3/run_alphafold.py", line 678, in <module>
    app.run(main)
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/root/alphafold3/run_alphafold.py", line 663, in main
    process_fold_input(
  File "/root/alphafold3/run_alphafold.py", line 542, in process_fold_input
    all_inference_results = predict_structure(
                            ^^^^^^^^^^^^^^^^^^
  File "/root/alphafold3/run_alphafold.py", line 362, in predict_structure
    featurised_examples = featurisation.featurise_input(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/featurisation.py", line 62, in featurise_input
    validate_fold_input(fold_input)
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/featurisation.py", line 28, in validate_fold_input
    raise ValueError(f'Protein chain {i + 1} is missing unpaired MSA.')
ValueError: Protein chain 1 is missing unpaired MSA.


I think the output json from the norun_inference run looks weird, shouldn't there be some msa info in the json file?

**Comment by rukibuki** [comment]
okay never mind, I just reran the same files and now the output json file had the msa info included. So I don't know what happened but I must have made a mistake in the initial run. So I will go ahead and close it.

**Comment by xuagu37** [comment]
The issue is that the JSON file gets overwritten by the original input when the GPU step is performed using the original JSON as input.

**Comment by paulasanematsu** [comment]
I came across the same error when using `--norun_data_pipeline`

```
Traceback (most recent call last):
  File "/app/alphafold/run_alphafold.py", line 678, in <module>
    app.run(main)
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/app/alphafold/run_alphafold.py", line 663, in main
    process_fold_input(
  File "/app/alphafold/run_alphafold.py", line 542, in process_fold_input
    all_inference_results = predict_structure(
                            ^^^^^^^^^^^^^^^^^^
  File "/app/alphafold/run_alphafold.py", line 362, in predict_structure
    featurised_examples = featurisation.featurise_input(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/featurisation.py", line 62, in featurise_input
    validate_fold_input(fold_input)
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/featurisation.py", line 28, in validate_fold_input
    raise ValueError(f'Protein chain {i + 1} is missing unpaired MSA.')
ValueError: Protein chain 1 is missing unpaired MSA.
```

The problem was that I had `--input_dir` pointing to a different directory than what the `--json_path` was. 

To run the [`2pv7`  example](https://github.com/google-deepmind/alphafold3?tab=readme-ov-file#installation-and-running-your-first-prediction) with `--norun_data_pipeline`, you can resolve by either:

1. Use `--input_dir=/path/to/2pv7` and `--json_path=/path/to/2pv7/2pv7_data.json`
2. Only use `--json_path=/path/to/2pv7/2pv7_data.json`
